# Generated by Django 4.2.1 on 2023-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
